#!/bin/bash
####
#a) Define slurm job parameters
####

SBATCH --job-name=ShortSlurmTest_Bisuit

#resources:

SBATCH --cpus-per-task=1
# the job can use and see 4 CPUs (from max 24).

SBATCH --partition=test
# the slurm partition the job is queued to.

SBATCH --mem-per-cpu=1G
# the job will need 12GB of memory equally distributed on 4 cpus.(251GB are available in total on one node)

SBATCH --gres=gpu:0
#the job can use and see 1 GPUs (4 GPUs are available in total on one node) use SBATCH --gres=gpu:1080ti:1 to explicitly demand a Geforce 1080 Ti GPU. Use SBATCH --gres=gpu:A4000:1 to explicitly demand a RTX A4000 GPU

SBATCH --time=00:30
# the maximum time the scripts needs to run
# "minutes:seconds", "hours:minutes:seconds", "days-hours","days-hours:minutes" and "days-hours:minutes:seconds"

SBATCH --error=job.%J.err
# write the error output to job.*jobID*.err

SBATCH --output=job.%J.out
# write the standard output to job.*jobID*.out

SBATCH --mail-type=ALL
#write a mail if a job begins, ends, fails, gets requeued or stages out

SBATCH --mail-user=lennart.slusny@student.uni-tuebingen.de
# your mail address

####
#b) copy all needed data to the jobs scratch folder
# We copy the cifar10 datasets which is already available in common datasets folder to our job’s scratch folder.
# Note: For this script, cifar-10 would be downloaded directly from internet, if you didn't copy it yourself.
#### 

# cp -R /common/datasets/cifar_tutorial/ /scratch/$SLURM_JOB_ID/

####
#c) Execute your code in a specific singularity container
#d) Write your checkpoints to your home directory, so that you still have them if your job fails
####

# singularity exec --nv
# /common/singularityImages/TCML-Cuda11_0_TF2_4_1_PT1_7_1.simg python
# cifar_tutorial.py /scratch/$SLURM_JOB_ID/cifar_tutorial/
./test_internet.sh

echo DONE!